SCHEMA ::= NAMESPACE_DECL SCHEMA_HEADER_DUMMY_TABLE

SCHEMA_HEADER_DUMMY_TABLE ::= 'table' WS IDENTIFIER WS '{' IDENTIFIER ':' BOOL_TYPE '}'

NAMESPACE_DECL ::= 'namespace' WS ((IDENTIFIER '.' IDENTIFIER) | IDENTIFIER) WS ';' NL

IDENTIFIER ::= [a-zA-Z_][a-zA-Z0-9_]*

BOOL_TYPE ::= 'bool'

WS ::= ' '
NL ::= '\n'
